# start of run config
- hosts: localhost
  connection: local
  tags: always
  become: true
  ignore_errors: yes
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - include: tasks/users.yml
  - include: tasks/cron.yml
  - include: tasks/packages.yml
  - include: tasks/usbguard.yml
  - include: tasks/firefox.yml
  - include: tasks/time_and_timezone.yml
#  - include: tasks/disable_adminuser.yml

# end of run cleanup and reporting
- hosts: localhost
  become: true
  tasks:
  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]