- hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - inclue: tasks/packages.yml
