- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install essential packages
  apt:
    name:
    #  - libreoffice
    state: latest

- name: Remove LibreOffice
  package:
    name: libreoffice
    state: absent