# tasks/time_and_timezone.yml

- name: Set timezone to Madrid, Spain
  timezone:
    name: "Europe/Madrid"

- name: Install language packs for UK English
  apt:
    name: "language-pack-en"
    state: present

- name: Set system language to UK English
  locale_gen:
    name: "en_GB.UTF-8"
    state: present

- name: Update system locale
  command: update-locale LANG=en_GB.UTF-8
