---
- name: Update all Ubuntu systems and enable unattended-upgrades
  hosts: ubuntu_servers
  become: true  # Run tasks with elevated privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades
      template:
        src: files/50unattended-upgrades
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
      notify: Restart unattended-upgrades

  handlers:
    - name: Restart unattended-upgrades
      service:
        name: unattended-upgrades
        state: restarted
